### ISSUE TITLE
Labelled.translate hangs

### ISSUE THREAD

**Issue by zenhack** [sshine/evm-opcodes#3]
...on even trivial inputs (afaik anything but `[]`):

```
$ cabal repl --build-depends=evm-opcodes
ghci> import EVM.Opcodes
ghci> import qualified EVM.Opcodes.Labelled as L
ghci> :set -XOverloadedStrings
ghci> L.translate [ADD]
Right [
```

On my machine the above results in ghci eventually being SIGKILLed due to an out of memory error. The problem was not obvious to me from looking at the source code.

**Comment by sshine** [comment]
Hi @zenhack,

Thank you for paying an interest and for discovering a bug that could have been caught with basic testing.

I'll try and fix the bug.
